services:

  broker:
    build:
      context: .
      dockerfile: Dockerfile
    image: cc7261:pyzmq
    container_name: broker
    volumes:
      - ./broker.py:/app/main.py
    ports:
      - "5555:5555"
      - "5556:5556"

  pubsub-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: cc7261:pyzmq
    container_name: pubsub-proxy
    volumes:
      - ./pubsub_proxy.py:/app/main.py
    ports:
      - "5557:5557"
      - "5558:5558"

  reference:
    build:
      context: .
      dockerfile: Dockerfile
    image: cc7261:pyzmq
    container_name: reference
    volumes:
      - ./reference.py:/app/main.py
    ports:
      - "5559:5559"

  servidor:
    build:
      context: .
      dockerfile: Dockerfile
    image: cc7261:pyzmq
    volumes:
      - ./servidor.py:/app/main.py
      - servidor_data:/app
    environment:
      - SERVER_NAME=servidor-py
    depends_on:
      - broker
      - pubsub-proxy
      - reference

  cliente:
    build:
      context: .
      dockerfile: Dockerfile
    image: cc7261:pyzmq
    volumes:
      - ./cliente.py:/app/main.py
    depends_on:
      - broker
      - pubsub-proxy
      - servidor

  servidor-java:
    build:
      context: ./java
      dockerfile: Dockerfile
    image: cc7261:java
    environment:
      - APP_MODE=servidor
      - SERVER_NAME=servidor-java
    volumes:
      - servidor_java_data:/data
    depends_on:
      - broker
      - pubsub-proxy
      - reference

  cliente-java:
    build:
      context: ./java
      dockerfile: Dockerfile
    image: cc7261:java
    environment:
      - APP_MODE=cliente
    depends_on:
      - broker
      - pubsub-proxy
      - servidor-java

volumes:
  servidor_data:
  servidor_java_data:
